name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Permissions needed for gh-pages deployment
permissions:
  contents: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Setup Git identity for gh-pages
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      # Deploy using the gh-pages package via npm script
      - name: Deploy with gh-pages
        env:
          # Use the personal access token for deployment
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set the token for gh-pages to use
          git remote set-url origin https://git:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy 